import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker/index.mjs';
import {adminPage} from '../worker/ui.mjs';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:')}
 prepare(sql){const db=this.db;let args=[];return {bind(...v){args=v;return this},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},async run(){db.prepare(sql).run(...args);return {success:true}}}}
 async batch(statements){let results=[];for(const s of statements)results.push(await s.all());return results}
}
const host='https://fiberboom.com';
const env=()=>({DB:new D1(),ADMIN_PIN:'test-only-pin',SESSION_SECRET:'test-only-secret-of-at-least-32-characters',ASSETS:{fetch:async()=>new Response('asset')}});
const req=(path,body,cookie)=>new Request(host+path,{method:body?'POST':'GET',headers:{Origin:host,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
async function login(e){const r=await worker.fetch(req('/api/admin/login',{pin:e.ADMIN_PIN}),e);assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
const event=(overrides={})=>({id:crypto.randomUUID(),visitor:crypto.randomUUID(),session:crypto.randomUUID(),page:crypto.randomUUID(),seq:1,name:'page_view',path:'/',active:0,scroll:0,time:Date.now(),details:{persistent:true},...overrides});
test('missing setup fails closed; public pages still work',async()=>{const e=env();delete e.DB;assert.equal((await worker.fetch(req('/api/events',{events:[event()]}),e)).status,503);assert.equal(await (await worker.fetch(req('/'),e)).text(),'asset');assert.match(await (await worker.fetch(req('/admin'),e)).text(),/Setup required/)});
test('authentication, secure cookie, tampering, origin checks, rate limiting',async()=>{const e=env();assert.equal((await worker.fetch(req('/api/admin/report'),e)).status,401);assert.equal((await worker.fetch(req('/api/admin/login',{pin:'wrong'}),e)).status,401);const r=await worker.fetch(req('/api/admin/login',{pin:e.ADMIN_PIN}),e);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);const cookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await worker.fetch(req('/api/admin/report',null,cookie+'a'),e)).status,401);assert.equal((await worker.fetch(new Request(host+'/api/events',{method:'POST',headers:{Origin:'https://evil.test'},body:'{}'}),e)).status,403);for(let i=0;i<4;i++)await worker.fetch(req('/api/admin/login',{pin:'wrong'}),e);assert.equal((await worker.fetch(req('/api/admin/login',{pin:e.ADMIN_PIN}),e)).status,429)});
test('events persist once; maxima, returning visits, filters and journeys calculate correctly',async()=>{const e=env();const first=event();const second=event({visitor:first.visitor,path:'/boom/en/'});const engaged=event({visitor:first.visitor,session:first.session,page:first.page,name:'active_time',seq:2,active:600,scroll:80});const batch={events:[first,second,engaged]};assert.equal((await worker.fetch(req('/api/events',batch),e)).status,200);await worker.fetch(req('/api/events',batch),e);const cookie=await login(e);const report=await (await worker.fetch(req('/api/admin/report',null,cookie),e)).json();assert.equal(report.totals.events,3);assert.equal(report.totals.views,2);assert.equal(report.totals.returning_browsers,1);assert.equal(report.visitors[0].lifetime_sessions,2);assert.equal(report.pages.find(p=>p.path==='/').active,600);const filtered=await (await worker.fetch(req('/api/admin/report?variant=boom',null,cookie),e)).json();assert.equal(filtered.totals.views,1);const journey=await (await worker.fetch(req('/api/admin/journey?visitor='+first.visitor,null,cookie),e)).json();assert.equal(journey.events.length,3);assert.equal((await worker.fetch(req('/api/events',{events:[event({path:'/admin'})]}),e)).status,400)});
test('daily retention cleanup deletes old events',async()=>{const e=env();await worker.fetch(req('/api/events',{events:[event()]}),e);e.DB.db.exec('UPDATE events SET received=1');await worker.scheduled({},e);assert.equal(e.DB.db.prepare('SELECT count(*) n FROM events').get().n,0)});
test('admin templates contain syntactically valid scripts without embedded PIN',()=>{for(const auth of [true,false]){const html=adminPage(auth,true,'nonce');const script=html.match(/<script nonce="nonce">([\s\S]*?)<\/script>/)[1];new Function(script);assert.ok(!html.includes('1201'));assert.ok(!html.includes('test-only-pin'))}});
