import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const script=readFileSync(new URL('../site/analytics.js',import.meta.url),'utf8');
function browser(storage=new Map(),start=Date.now(),search='?utm_source=invite&email=private'){
 let elapsed=0;const timers=[],handlers={},requests=[];const doc={hidden:false,documentElement:{lang:'en',scrollHeight:2000},referrer:'https://example.com/private?secret=yes',addEventListener:(n,f)=>handlers[n]=f,querySelector:()=>null};
 const context={crypto,URL,URLSearchParams,Date:class extends Date{static now(){return start+elapsed}},performance:{now:()=>elapsed},location:{pathname:'/',search,origin:'https://fiberboom.com'},document:doc,innerHeight:1000,scrollY:0,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setInterval:(f,ms)=>timers.push({f,ms}),addEventListener:(n,f)=>handlers[n]=f,requestAnimationFrame:f=>f(),fetch:async(url,options)=>{requests.push(JSON.parse(options.body));return {ok:true}}};vm.runInNewContext(script,context);
 return {doc,context,requests,handlers,async tick(seconds){for(let i=0;i<seconds;i++){elapsed+=1000;for(const t of timers)if(elapsed%t.ms===0)t.f();await Promise.resolve();await Promise.resolve()}},events(){return requests.flatMap(x=>x.events)}};
}
test('tracking starts without banner choice, caps time, excludes background time and sends scroll milestones',async()=>{const b=browser();await b.tick(30);b.doc.hidden=true;b.handlers.visibilitychange();await b.tick(300);b.doc.hidden=false;b.handlers.visibilitychange();await b.tick(30);assert.ok(b.events().every(e=>e.active<=60));b.context.scrollY=1000;b.handlers.scroll();await b.tick(600);assert.equal(Math.max(...b.events().map(e=>e.active)),600);assert.equal(b.events().filter(e=>e.name==='scroll_depth').length,10);assert.equal(b.events().find(e=>e.name==='page_view').details.referrer,'example.com');assert.ok(!JSON.stringify(b.events()).includes('private'));assert.ok(!JSON.stringify(b.events()).includes('email='))});
test('returning browser retains visitor but gets new session after idle timeout',async()=>{const storage=new Map(),now=Date.now();const a=browser(storage,now),b=browser(storage,now+31*60000);assert.equal(a.events()[0].visitor,b.events()[0].visitor);assert.notEqual(a.events()[0].session,b.events()[0].session);assert.notEqual(a.events()[0].page,b.events()[0].page)});

test('UTMs persist across pages and events, reset on new tagged links and expire with session',async()=>{const storage=new Map(),now=Date.now();const a=browser(storage,now,'?utm_source=newsletter&utm_medium=email&utm_campaign=Launch%20A&utm_content=hero&utm_term=fiber');await a.tick(15);assert.equal(a.events().find(e=>e.name==='active_time').details.utm_campaign,'Launch A');const b=browser(storage,now+20000,'');assert.equal(b.events()[0].details.utm_source,'newsletter');assert.equal(b.events()[0].details.utm_content,'hero');const c=browser(storage,now+21000,'?utm_source=instagram&utm_medium=paid');assert.equal(c.events()[0].details.utm_source,'instagram');assert.equal(c.events()[0].details.utm_campaign,undefined);await a.tick(15);const d=browser(storage,now+40000,'');assert.equal(d.events()[0].details.utm_source,'instagram');const expired=browser(storage,now+32*60000,'');assert.equal(expired.events()[0].details.utm_source,undefined)});

test('privacy notice choices and policy link are tracked once without interrupting engagement',async()=>{
 const b=browser();await b.tick(1);
 for(const [id,tagName,label] of [['fb-beta-notice-decline','BUTTON','Decline'],['fb-beta-notice-dismiss','BUTTON','Dismiss'],['','A','Privacy Policy']]){
  const target={id,tagName,textContent:label,closest:selector=>selector==='#fb-beta-notice'?{}:target};b.handlers.click({target});await b.tick(1);
 }
 assert.deepEqual(b.events().filter(e=>e.name.startsWith('privacy_notice_')).map(e=>e.name),['privacy_notice_declined','privacy_notice_dismissed','privacy_notice_policy_click']);
 await b.tick(30);assert.ok(b.events().some(e=>e.name==='active_time'&&e.active>=15));assert.ok(b.events().filter(e=>e.name.startsWith('privacy_notice_')).every(e=>e.details.utm_source==='invite'&&e.path==='/'));
});
