import {mkdir,readFile,writeFile} from 'node:fs/promises';
export async function buildCommerce(){
const c=JSON.parse(await readFile('site/commerce/catalog.json','utf8'));
for(const [version,copy] of Object.entries(c.versions).filter(([version])=>!version.endsWith('x'))){
const root=`/${version}/en`;const flavour=c.flavors.chocolate;
const header=`<a class="skip" href="#main">Skip to content</a><header class="product-header"><a href="${root}/" aria-label="FiberBoom home"><img class="logo" src="/assets/logo-3e78513a6041.webp" alt="FiberBoom" width="123" height="92"></a></header>`;
const footer=`<footer class="site-footer"><div class="footer-brand"><img src="/assets/footer-logo-v5-be2bf9b2381a.webp" alt="FiberBoom" width="150" height="112" loading="lazy"><p>${copy.footer}</p><small>© 2026 Fiberboom</small></div><div class="footer-info"><div class="footer-links"><a href="/privacy/en/">Privacy policy</a><a href="/terms/en/">Terms &amp; conditions</a><a href="mailto:contact@fiberboom.com">Contact</a></div><p>Fiberboom<br>Svanevej 22, 2400 København, Denmark</p><a href="mailto:contact@fiberboom.com">contact@fiberboom.com</a></div></footer>`;
const selector=`<fieldset><legend>01 &nbsp; Choose your flavour</legend><div class="flavors">${Object.entries(c.flavors).map(([id,f])=>`<button type="button" class="flavor ${id==='chocolate'?'selected':''}" data-flavor="${id}" aria-pressed="${id==='chocolate'}"><img src="${f.pack}" alt="" width="120" height="120" loading="lazy"><span>${f.name}</span></button>`).join('')}</div></fieldset><fieldset><legend>02 &nbsp; Choose your pack</legend><div class="packs">${c.packs.map(n=>`<button type="button" data-pack="${n}" class="pack ${n===14?'selected':''}" aria-pressed="${n===14}"><strong>${n} bars</strong><span data-pack-price="${n}"></span><small data-unit-price="${n}"></small></button>`).join('')}</div></fieldset>`;
const details=`<section id="product-details" class="product-story"><div class="story-copy"><h2 id="detail-name"></h2><p id="detail-description"></p><p>Psyllium husk, in a bar that tastes great. Enjoy with a generous glass of water.</p><a href="#ingredients-panel">Explore ingredients & nutrition ↓</a></div><img id="story-bar" src="${flavour.bar}" alt="Dark Chocolate bar" width="600" height="450" loading="lazy"></section><section class="accordions product-facts" aria-label="Product information"><details id="ingredients-panel" data-detail="ingredients"><summary>Ingredients & allergens</summary><p id="ingredients"></p><p id="allergens" class="allergens"></p><small class="ingredient-note">Provisional product information: ingredients, allergens and nutrition are not yet verified.</small></details><details data-detail="nutrition"><summary>Nutrition information</summary><small class="ingredient-note">Provisional values, subject to verification.</small><table><thead><tr><th scope="col">Typical values</th><th scope="col">Per 100 g</th><th scope="col">Per 45 g bar</th></tr></thead><tbody id="nutrition"></tbody></table></details><details data-detail="shipping"><summary id="delivery-title">Delivery</summary><p id="delivery-description"></p><p id="delivery-cost"></p><p id="shipping-policy">The free-delivery threshold applies to the value of your bars after discounts, excluding delivery. Delivery is charged once per order.</p></details><details data-detail="payment"><summary>Payment methods</summary><div id="payment-details" class="payment-tags"></div><p>Choose the payment method that suits you. Availability depends on your delivery country, currency and device. Wallets require a compatible device; Klarna options are subject to eligibility. Bank transfers and SEPA Direct Debit can take additional time to clear.</p></details><details data-detail="returns"><summary>Returns & refunds</summary><p>Changed your mind? Contact us within 14 days of receiving your order to request a return. Email contact@fiberboom.com with your order number and the items you want to return. Keep the bars in their original packaging and send them back within 14 days of notifying us. You cover return postage for a change-of-mind return.</p><p>Refunds go back to the original payment method, including standard outbound delivery where required. We refund within 14 days of your cancellation notice, but may wait until we receive the goods or proof of return. Exceptions can apply to quickly perishable products and sealed goods unsealed after delivery where the hygiene exception applies.</p><p>Damaged, faulty or incorrect items? <a href="mailto:contact@fiberboom.com">Contact us</a> so we can put things right. Your statutory rights are unaffected.</p></details></section>`;
const popup=`<dialog id="restock-dialog" aria-labelledby="restock-title"><button class="dialog-close" type="button" aria-label="Close restock message">×</button><div class="restock-art"><img id="restock-image" src="${flavour.pack}" alt="Your selected FiberBoom flavour" width="220" height="220"><span>GOOD THINGS<br>TAKE A LITTLE<br>FIBRE.</span></div><div class="restock-copy"><p class="eyebrow">CURRENTLY UNAVAILABLE</p><h2 id="restock-title">Oh, poop.<br>We're out of stock.</h2><p>Our bars are taking a little bathroom break. We're working on the next batch — want first dibs?</p><div class="discount"><strong>30% OFF</strong><span>your first order when we're back.</span></div><p class="restock-promise">We’ll email you when we’re back, with 30% off your first order.</p><form id="restock-form" onsubmit="return false"><label for="restock-email">Your email</label><input id="restock-email" type="email" autocomplete="email" placeholder="you@example.com" maxlength="254" required><button class="primary full" type="submit">Get 30% discount ↗</button><p class="consent-copy">By signing up, you agree to receive a restock email and your 30% offer from Fiberboom. Unsubscribe anytime by emailing <a href="mailto:privacy@fiberboom.com">privacy@fiberboom.com</a>. <a href="/privacy/en/">Privacy policy</a>.</p></form><p id="restock-status" role="status" aria-live="polite"></p></div></dialog>`;
const product=`<main id="main"><section class="product-layout"><div class="gallery"><div class="gallery-main"><span class="gallery-stamp">FIBRE.<br>WITH FLAVOUR.</span><img id="product-image" src="${flavour.box}" alt="Dark Chocolate Fiberboom box" width="900" height="900" fetchpriority="high"><span class="gallery-caption" id="gallery-caption">Dark Chocolate · 14 bars</span></div><div class="thumbnails" aria-label="Product images"><button type="button" data-view="box" aria-pressed="true"><img id="thumb-box" src="${flavour.box}" alt="View box" width="120" height="120" loading="lazy"></button><button type="button" data-view="pack" aria-pressed="false"><img id="thumb-pack" src="${flavour.pack}" alt="View package" width="120" height="120" loading="lazy"></button><button type="button" data-view="bar" aria-pressed="false"><img id="thumb-bar" src="${flavour.bar}" alt="View bar" width="120" height="120" loading="lazy"></button></div></div><div class="product-buy"><h1>${copy.title}</h1><p class="intro">${copy.description}</p>${selector}<div class="price-line" aria-live="polite"><strong id="price"></strong><span id="per-bar"></span></div><a class="primary full" id="to-checkout" href="${root}/checkout/">Order now <span>↗</span></a><p id="shipping-summary" class="shipping-summary" aria-live="polite"></p><div class="near-payments"><small>Payment options</small><div id="payment-near" class="payment-tags"></div></div></div></section>${details}</main><div class="mobile-buy"><span id="mobile-price"></span><a class="primary" id="mobile-checkout" href="${root}/checkout/">Order now ↗</a></div>`;
for(const [kind,body] of [['product',product]]){
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${kind==='product'?'Choose your fibre bars':'Checkout'} | Fiberboom ${version}</title><meta name="description" content="Choose your Fiberboom flavour and pack size. Explore flavours, ingredients and nutrition."><link rel="canonical" href="https://fiberboom.com${root}/${kind}/"><link rel="stylesheet" href="/commerce/style.css"><link rel="stylesheet" href="/legal-links.css"></head><body class="theme-${version}" data-commerce-page="${kind}" data-version="${version}">${header}${body}${footer}${popup}<script type="module" src="/commerce/app.js"></script></body></html>`;
 await mkdir(`dist/${version}/en/${kind}`,{recursive:true});await writeFile(`dist/${version}/en/${kind}/index.html`,html);
}
}
}
